#!/bin/sh
#
# stamat_hourly cron hourly

LOGFILE='fetch.log'

echo 'go get them, tiger!'
wget --timeout=0 -O - 'http://fom.londondroids.com/stamat/index.php/api/fetch_store_all_feeds' > $LOGFILE
echo '' >> $LOGFILE
# cat $LOGFILE | mail -s "STAMAT hourly fetch" thomasalisi@gmail.com
rm -f $LOGFILE
